# Generated by Django 3.1.4 on 2021-01-26 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okb2', '0001_initial'),
        ('hospital', '0003_auto_20210126_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sluchay',
            name='c_zab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='okb2.v027'),
        ),
    ]
