# Generated by Django 3.1.4 on 2021-01-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20210126_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sluchay',
            name='onk_sl',
        ),
        migrations.AddField(
            model_name='sluchay',
            name='onk_sl',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.onk_sl'),
        ),
    ]
