# Generated by Django 3.1.4 on 2021-01-27 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20210126_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_diag',
            name='rec_rslt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='sluchay',
            name='b_diag',
        ),
        migrations.AddField(
            model_name='sluchay',
            name='b_diag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.b_diag'),
        ),
    ]
