# Generated by Django 3.1.4 on 2021-01-27 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20210127_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sluchay',
            name='cons',
        ),
        migrations.AddField(
            model_name='sluchay',
            name='cons',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.cons'),
        ),
    ]
