# Generated by Django 3.1.4 on 2021-01-27 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_auto_20210127_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='napr',
            old_name='napr_date',
            new_name='naprdate',
        ),
        migrations.RemoveField(
            model_name='sluchay',
            name='napr',
        ),
        migrations.AddField(
            model_name='sluchay',
            name='napr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.napr'),
        ),
    ]
